# Generated by Django 3.1.1 on 2020-10-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('psno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=50)),
                ('content', models.TextField(max_length=5000)),
                ('slug', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(default='', upload_to='images')),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
