# Generated by Django 3.1.1 on 2020-10-14 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='timestamp',
        ),
    ]
